language: cpp

env:
  - CMAKE_BUILD_TYPE=Debug

compiler:
  - gcc
  - clang

os:
  #  - linux
  - osx

sudo: required

dist: trusty

before_install:
  - if [ "$TRAVIS_OS_NAME" = linux ]; then apt-get install -qq ragel ; fi
  - if [ "$TRAVIS_OS_NAME" = osx   ]; then brew update ; fi
  - if [ "$TRAVIS_OS_NAME" = osx   ]; then brew install ragel ; fi
  - if [ "$TRAVIS_OS_NAME" = osx   ]; then brew install ninja ; fi
  - if [ "$TRAVIS_OS_NAME" = osx   ]; then brew install libxml2 ; fi
  # brew complains:
  # Error: boost-1.55.0_2 already installed
  # To install this version, first `brew unlink boost`
  # ( -> we need at least 1.58)
  - if [ "$TRAVIS_OS_NAME" = osx   ]; then brew unlink boost ; fi
  - if [ "$TRAVIS_OS_NAME" = osx   ]; then brew install boost ; fi
  # they come with 4.9.1 by default but since we are already upgrading boost
  - if [ "$TRAVIS_OS_NAME" = osx -a "$CXX" = g++  ]; then brew unlink gcc ; fi
  - if [ "$TRAVIS_OS_NAME" = osx -a "$CXX" = g++  ]; then brew install gcc ; fi
  - if [ "$TRAVIS_OS_NAME" = osx -a "$CXX" = clang++  ]; then brew install llvm ; fi

#install:

# XXX what BOOST_ROOT with Mac OSX Brew?
before_script:
  - mkdir build
  - cd build
  # PWD -> build
  - if [ "$TRAVIS_OS_NAME" = osx -a "$CXX" = g++  ]; then CXX=/usr/local/bin/g++ CC=/usr/local/bin/gcc cmake -G Ninja -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE .. ; fi
  - if [ "$TRAVIS_OS_NAME" = osx -a "$CXX" = clang++  ]; then CXX=$(brew --prefix llvm)/bin/clang++ CC=$(brew --prefix llvm)/bin/clang cmake -G Ninja -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE .. ; fi

# PWD -> build
script: ninja -j1 bed ut && ./ut
