# Mac OS X notes (2018-09)
#
# - current Travis CI environment is Mac OS X 10.13
#   cf. https://docs.travis-ci.com/user/reference/osx/#os-x-version
# - current Boost from Homebrew is 1.67 (available by default)

# Ubuntu Trusty notes
#
# - default GCC is too old (4.8)
# - default Boost is too old (1.54)


sudo: required

#dist: trusty

#os:
# TODO enable linux in build matrix
#  - linux

language: cpp

git:
    submodules: false

# as of 2018-09 - default is xcode9.4
#osx_image: xcode10

matrix:
  include:
    # the default xcode clang is good enough as of 2018-09
    - os: osx
      compiler: clang
      env: CMAKE_BUILD_TYPE=Debug MY_CXX=clang++ MY_CC=clang MY_CXXFLAGS='-Og'
    # with clang 3.7 from Homebrew, the libclang_rt.profile_osx.a os
    # not available ... thus linking fails - perhaps it works with xcode clang
    # - os: osx
    #  compiler: clang
    #  env: CMAKE_BUILD_TYPE=Coverage MY_CXX=clang++ MY_CC=clang
    - os: osx
      compiler: clang
      env: CMAKE_BUILD_TYPE=Release MY_CXX=clang++ MY_CC=clang MY_CXXFLAGS='-fsanitize=address'
    - os: linux
      services: docker
      env: docker_image=gsauthof/fedora-cxx-devel:27 build_tag=linux CMAKE_BUILD_TYPE=SanitizeO
    - os: linux
      services: docker
      env: docker_image=gsauthof/fedora-cxx-devel:27 build_tag=linux CMAKE_BUILD_TYPE=Coverage
    - os: linux
      services: docker
      env: docker_image=gsauthof/fedora-mingw64-devel:27 docker_image_b=gsauthof/fedora-mingw64-runtime:27 build_tag=mingw64 CMAKE_BUILD_TYPE=Release


before_install:
    - git submodule update --init
    - ./ci/travis/before_install.sh

install:
  - ./ci/travis/install.sh

before_script:
  - ./ci/travis/before_script.sh

script:
  - ./ci/travis/script.sh

after_success:
  - ./ci/travis/after_success.sh

#after_failure:

#before_deploy:

#deploy:

#after_deploy:

after_script:
  - ./ci/travis/after_script.sh
