language: cpp

env:
  - CMAKE_BUILD_TYPE=Debug

compiler:
  - gcc
  - clang

os:
  #  - linux
  - osx

sudo: required

dist: trusty

before_install:
  - if [ "$TRAVIS_OS_NAME" = linux ]; then apt-get install -qq ragel ; fi
  - if [ "$TRAVIS_OS_NAME" = osx   ]; then brew update ; fi
  - if [ "$TRAVIS_OS_NAME" = osx   ]; then brew install ragel ; fi
  - if [ "$TRAVIS_OS_NAME" = osx   ]; then brew install ninja ; fi
  - if [ "$TRAVIS_OS_NAME" = osx   ]; then brew install libxml2 ; fi
  - if [ "$TRAVIS_OS_NAME" = osx   ]; then brew install boost ; fi

#install:

before_script:
  - mkdir build
  - cd build
  # PWD -> build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE ..

# PWD -> build
script: ninja -j1 bed ut && ./ut
